
services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - ./store/configdb:/data/configdb
      - ./store/db:/data/db
    ports:
      - "27017:27017"
    user: root
  payload:
    build: ./payload
    ports:
      - "3000:3000"
    volumes:
      - ./payload/upload:/app/upload
    environment:
      DATABASE_URL: mongodb://172.17.0.1:27017/koston-setup
      PAYLOAD_SECRET: KIMIMA
      IN_DOCKER: 1
  website:
    build: ./
    ports:
      - "4321:4321"
    environment:
      DATABASE_URL: mongodb://172.17.0.1:27017/koston-setup
      PAYLOAD_SECRET: KIMIMA
      IN_DOCKER: 1