packages:
  - payload
  - website

ignoredBuiltDependencies:
  - esbuild

linkWorkspacePackages: true
dangerouslyAllowAllBuilds: all
supportedArchitectures:
  os:
  - linux
  - current
  cpu:
  - x64
  libc:
  - musl
  - glibc