server {
  listen 80;
  server_name msy.com;

  location /upload/ {
    alias /app/upload/;
  }

  location /_astro/ {
    root /app/astro/;
    expires 30d;
    add_header Cache-Control "public";
  }

  location /favicon.ico {
    root /app/astro/;
  }

  location /_next {
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # docker default host machine ip
    proxy_pass http://172.17.0.1:6300;
  }

  location /admin {
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # docker default host machine ip
    proxy_pass http://172.17.0.1:6300;
  }

  location /api {
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # docker default host machine ip
    proxy_pass http://172.17.0.1:6300;
  }

  location / {
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # docker default host machine ip
    proxy_pass http://172.17.0.1:6321;
  }
}